export const ASYNC_ACTION_START = "ASYNC_ACTION_START";
export const ASYNC_ACTION_FINISH = "ASYNC_ACTION_FINISH";
export const ASYNC_ACTION_ERROR = "ASYNC_ACTION_ERROR";
export const FETCH_LOCATIONS = "FETCH_LOCATIONS";
export const DELETE_LOCATION = "DELETE_LOCATION";
export const FETCH_SETUPS = "FETCH_SETUPS";
